# Pre Masters Maths 6601PMEC

## Examples of Using SymPy for Trigonometric Functions

9. Solve the following trigonometrical equations in the ranges given:  
  a) $\sin (\theta) = 0.7506 \quad 0 \leq \theta \leq 360^o$

In [1]:
from sympy import *
import numpy as np
init_printing()

In [2]:
from sympy.physics.units import *
th = symbols('theta', real=True)
sol = solve(sin(th)-0.7506)
sol

The only issue with this solution is that it is in radians not degrees. Because SymPy, by default, gives answers in radians, this set of solutions needs to be converted. We could use a _for_ loop to convert each element to degrees:

In [3]:
for i in sol:
    print(i*180/pi.n())

48.6423785006708
131.357621499329


Or the NumPy _array_ command could be used, which is argueably much more simple to implement.

In [4]:
np.array(sol) * 180/np.pi

array([48.6423785006708, 131.357621499329], dtype=object)

The NumPy library also has a command, _rad2deg_ that will convert the numerical solution from radians to degrees. Just make sure that the array is forced to a _float_ data type using the _dtype_ flag.

In [5]:
np.rad2deg(np.array(sol, dtype=float))

array([ 48.6423785, 131.3576215])

b)  $\cos(t) = 0.4500 \quad 0 \leq t \leq 2 \pi$

In [6]:
t = symbols('t')
solve( cos(t) - 0.4500 )

Or in exact format...

In [7]:
t = symbols('t')
solve( cos(t) - Rational("0.4500") )

d) $\sin(3\theta) = -0.2556 \quad 0 \leq \theta \leq 180^o$

In [8]:
sol = solve( sin(3*th) + 0.2556 )
sol2 = np.array(sol, dtype=float)
np.rad2deg(sol2)

array([-4.93638029, 64.93638029])

The standard _solve_ command no longer works due to the solutions being 'outside' of the specified domain.  
  
  To overcome this, the _solveset_ command is used instead. The argument _Interval(lower_limit, higher_limit)_ can be used to specify the domain.

In [9]:
solveset( sin(3*th) + 0.2556, th, Interval(0, pi) ).n()

Again, this solution needs to be converted to degrees...

In [10]:
sol = list( solveset( sin(3*th) + 0.2556, th, Interval(0, pi) ).n() )
sol2 = np.array(sol, dtype=float)
np.rad2deg(sol2)

array([ 64.93638029, 115.06361971])

10.  Solve the following trigonometrical equations in the ranges given:  
  b) $\sin^2 (\theta) - 6 \sin(\theta) =  -4 \quad 0 \leq \theta \leq 720^o$

In [11]:
sol = list(solveset( sin(th)**2 - 6*sin(th) + 4, th, Interval(0, 4*pi)))
sol2 = np.array(sol, dtype=float)
np.rad2deg(sol2)

array([ 49.81207336, 130.18792664, 409.81207336, 490.18792664])

***   
  
by Dr J T Wharton

***